export enum GameEvent {
  StartScreensaver = 'StartScreensaver',
  StartThemeList = 'StartThemeList',
  StartThemeListInRound = 'StartThemeListInRound',
  StartRoundName = 'StartRoundName',
  StartTable = 'StartTable',
  StartQuestion = 'StartQuestion',
  StartQuestionPreparation = 'StartQuestionPreparation',
  StartResults = 'StartResults',
  UpdatePage = 'UpdatePage',
  UpdatePlayers = 'UpdatePlayers',
  QueuePlayersUpdated = 'QueuePlayersUpdated',
  UpdateScoreValue = 'UpdateScoreValue',
  Exit = 'Exit',
  UpdateMediaPlayer = 'OnUpdateMediaPlayer',
}
