export enum GameEvent {
  StartScreensaver = 'StartScreensaver',
  StartThemeList = 'StartThemeList',
  StartThemeListInRound = 'StartThemeListInRound',
  StartRoundName = 'StartRoundName',
  StartTable = 'StartTable',
  StartQuestion = 'StartQuestion',
  StartQuestionPreparation = 'StartQuestionPreparation',
  StartResults = 'StartResults',
  StartResultsOnCloseAllQuestions = 'StartResultsOnCloseAllQuestions',
  OpenQuestion = 'OpenQuestion',
  CloseQuestion = 'CloseQuestion',
  NextRound = 'NextRound',
  PreviousRound = 'PreviousRound',
  UpdatePage = 'UpdatePage',
  EnterQuestion = 'EnterQuestion',
  UpdatePlayers = 'UpdatePlayers',
  QueuePlayersUpdated = 'QueuePlayersUpdated',
  UpdateScoreValue = 'UpdateScoreValue',
  Exit = 'Exit',
  UpdateMediaPlayer = 'OnUpdateMediaPlayer',
}
